### ISSUE TITLE
Theme material design doesn't work properly

### ISSUE THREAD

**Issue by Hydrog3n** [Hydrog3n/dockerfiles#1]
Login page crash : 

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function ban_canLogin(), 0 passed in /shaarli/tmp/loginform.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 5 and exactly 1 expected in /shaarli/index.php:383 
Stack trace: #0 /shaarli/tmp/loginform.aeadca0864f49f08401fb0f97c162898.rtpl.php(5): ban_canLogin()
#1 /shaarli/inc/rain.tpl.class.php(175): include('/shaarli/tmp/lo...') 
#2 /shaarli/application/PageBuilder.php(134): RainTPL->draw('loginform')
#3 /shaarli/index.php(800): PageBuilder->renderPage('loginform') 
#4 /shaarli/index.php(2219): renderPage(Object(ConfigManager), Object(PluginManager)) 
#5 {main} thrown in /shaarli/index.php on line 383
```

**Comment by Hydrog3n** [comment]
Use master instead of release 0.8.2 !
